//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackingSystem.DAL.EFDAL.EFBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarDiaryEvent
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
    }
}
