//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackingSystem.DAL.EFDAL.EFBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int Status { get; set; }
        public int Project { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public Nullable<int> StoryPoints { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual Project Project1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
