//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackingSystem.DAL.EFDAL.EFBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLogs
    {
        public int TaskId { get; set; }
        public System.DateTime Time { get; set; }
        public string FieldName { get; set; }
        public string UserLogin { get; set; }
        public string ChangedValue { get; set; }
        public string NewValue { get; set; }
        public int Id { get; set; }
    }
}
